services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env        # ← baca dari file .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         # ← baca dari .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # ← baca dari .env
      POSTGRES_DB: ${POSTGRES_DB}             # ← baca dari .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: